server:
  port: 9990
  tomcat:
    uri-encoding: UTF-8
spring:
  profiles:
    active: dev
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          # serviceId统一使用小写字母
          lower-case-service-id: true
      routes:
        - id: server
          uri: lb://server
          predicates:
            - Path=/server/**
        - id: sdk
          uri: lb://sdk
          predicates:
            - Path=/sdk/**
        - id: dataview
          uri: lb://dataview
          predicates:
            - Path=/dataview/**
---
spring:
  profiles: dev
  cloud:
    nacos:
      discovery:
        server-addr: http://192.168.4.73:8848
---
spring:
  profiles: test
  cloud:
    nacos:
      discovery:
        server-addr: 10.240.48.52:8848
---
spring:
  profiles: prod
  cloud:
    nacos:
      discovery:
        server-addr: 10.240.48.53:8848